### ISSUE TITLE
speech transformer example error

### ISSUE THREAD

**Issue by ParkGiBum** [bytedance/neurst#42]
I am trying to follow example on speech transfomer with must-c 1.0 en-de dataset

python3 -m neurst.cli.run_exp \
    --config_paths /home/sylee/data/dataset/asr_st/de/asr_training_args.yml,/home/sylee/data/dataset/asr_st/de/asr_validation_args.yml \
    --hparams_set speech_transformer_s \
    --model_dir /home/sylee/data/dataset/asr_st/de/asr_benchmark

but it keeps making tensor conversion error as follow

sorry for elementary question
```
TypeError: Failed to convert object of type <class 'neurst.training.revised_dynamic_loss_scale.RevisedDynamicLossScale'> to Tensor. Contents: <neurst.training.revised_dynamic_loss_scale.RevisedDynamicLossScale object at 0x7f6b141da970>. Consider casting elements to a supported type.
Traceback (most recent call last):
  File "/home/sylee/.conda/envs/test2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sylee/.conda/envs/test2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 127, in <module>
    cli_main()
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 123, in cli_main
    app.run(_main, argv=["pseudo.py"])
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 118, in _main
    run_experiment(args, remaining_argv)
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 107, in run_experiment
    entry.run()
  File "/home/sylee/neurst/neurst/neurst/exps/trainer.py", line 294, in run
    history = keras_model.fit(
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/distribute/mirrored_strategy.py:670 _call_for_each_replica
        return mirrored_run.call_for_each_replica(
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/distribute/mirrored_run.py:104 call_for_each_replica
        return _call_for_each_replica(strategy, fn, args, kwargs)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/distribute/mirrored_run.py:246 _call_for_each_replica
        coord.join(threads)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/training/coordinator.py:389 join
        six.reraise(*self._exc_info_to_raise)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/six.py:703 reraise
        raise value
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/training/coordinator.py:297 stop_on_exception
        yield
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/distribute/mirrored_run.py:346 run
        self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/engine/training.py:791 train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py:520 minimize
        grads_and_vars = self._compute_gradients(
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py:676 _compute_gradients
        loss = self.get_scaled_loss(loss)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py:644 get_scaled_loss
        return loss * tf.cast(self.loss_scale, loss.dtype)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py:906 __getattribute__
        return object.__getattribute__(self, name)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py:568 loss_scale
        return tf.convert_to_tensor(self._loss_scale)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1430 convert_to_tensor_v2_with_dispatch
        return convert_to_tensor_v2(
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1436 convert_to_tensor_v2
        return convert_to_tensor(
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:271 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:288 _constant_impl
        tensor_util.make_tensor_proto(
    /home/sylee/.conda/envs/test2/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:551 make_tensor_proto
        raise TypeError("Failed to convert object of type %s to Tensor. "

    TypeError: Failed to convert object of type <class 'neurst.training.revised_dynamic_loss_scale.RevisedDynamicLossScale'> to Tensor. Contents: <neurst.training.revised_dynamic_loss_scale.RevisedDynamicLossScale object at 0x7f6b141da970>. Consider casting elements to a supported type.
```

**Comment by zhaocq-nlp** [comment]
@ParkGiBum Hi, could you please provide the version of your TensorFlow? The NeurST now works well on tensorflow==2.4.1

**Comment by ParkGiBum** [comment]
> @ParkGiBum Hi, could you please provide the version of your TensorFlow? The NeurST now works well on tensorflow==2.4.1


I have switched to tensorflow-gpu==2.4.1 from 2.7.0 and 

following error happens on python 3.7
```
I0104 15:21:13.353906 140589919109696 dataset_utils.py:330] Filtering empty data and datas exceeded max length={'audio': 240000, 'audio_length': -1, 'transcript': 120}
I0104 15:21:13.432794 140589919109696 speech2text.py:327] There are 29 input shapes to be compiled:
I0104 15:21:13.432915 140589919109696 speech2text.py:330]    - batch=944, maximum-frames=128, maximum-transcript-length={8, 16}
I0104 15:21:13.432966 140589919109696 speech2text.py:330]    - batch=472, maximum-frames=256, maximum-transcript-length={16, 24}
I0104 15:21:13.433010 140589919109696 speech2text.py:330]    - batch=312, maximum-frames=384, maximum-transcript-length={24}
I0104 15:21:13.433067 140589919109696 speech2text.py:330]    - batch=240, maximum-frames=512, maximum-transcript-length={24, 32}
I0104 15:21:13.433106 140589919109696 speech2text.py:330]    - batch=184, maximum-frames=656, maximum-transcript-length={32, 40}
I0104 15:21:13.433146 140589919109696 speech2text.py:330]    - batch=152, maximum-frames=800, maximum-transcript-length={40, 48}
I0104 15:21:13.433185 140589919109696 speech2text.py:330]    - batch=128, maximum-frames=944, maximum-transcript-length={48, 56}
I0104 15:21:13.433223 140589919109696 speech2text.py:330]    - batch=112, maximum-frames=1120, maximum-transcript-length={56}
I0104 15:21:13.433262 140589919109696 speech2text.py:330]    - batch=96, maximum-frames=1296, maximum-transcript-length={56, 64}
I0104 15:21:13.433301 140589919109696 speech2text.py:330]    - batch=88, maximum-frames=1472, maximum-transcript-length={64, 72}
I0104 15:21:13.433339 140589919109696 speech2text.py:330]    - batch=72, maximum-frames=1696, maximum-transcript-length={72, 80}
I0104 15:21:13.433378 140589919109696 speech2text.py:330]    - batch=64, maximum-frames=1920, maximum-transcript-length={80, 96}
I0104 15:21:13.433417 140589919109696 speech2text.py:330]    - batch=56, maximum-frames=2144, maximum-transcript-length={96, 104}
I0104 15:21:13.433456 140589919109696 speech2text.py:330]    - batch=56, maximum-frames=2432, maximum-transcript-length={104, 112}
I0104 15:21:13.433495 140589919109696 speech2text.py:330]    - batch=48, maximum-frames=2720, maximum-transcript-length={112, 120}
I0104 15:21:13.433534 140589919109696 speech2text.py:330]    - batch=40, maximum-frames=3008, maximum-transcript-length={120}
Traceback (most recent call last):
  File "/home/sylee/.conda/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 127, in <module>
    cli_main()
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 123, in cli_main
    app.run(_main, argv=["pseudo.py"])
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 118, in _main
    run_experiment(args, remaining_argv)
  File "/home/sylee/neurst/neurst/neurst/cli/run_exp.py", line 107, in run_experiment
    entry.run()
  File "/home/sylee/neurst/neurst/neurst/exps/trainer.py", line 206, in run
    model_out = self.model(formatted_inps, is_training=True)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in user code:

    /home/sylee/neurst/neurst/neurst/models/encoder_decoder_model.py:279 call  *
        generation_initializer["decoder_internal_cache"])
    /home/sylee/neurst/neurst/neurst/models/encoder_decoder_model.py:204 get_decoder_output  *
        decoder_output = self._decoder(inputs, cache, is_training=is_training,
    /home/sylee/neurst/neurst/neurst/layers/decoders/transformer_decoder.py:209 call  *
        decoder_self_attention_bias = layer_utils.lower_triangle_attention_bias(
    /home/sylee/neurst/neurst/neurst/layers/layer_utils.py:49 lower_triangle_attention_bias  *
        lower_triangle = tf.cast(
    /home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:3120 ones
        output = _constant_if_small(one, shape, dtype, name)
    /home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:2804 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:6 prod
        
    /home/sylee/.conda/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3052 prod
        keepdims=keepdims, initial=initial, where=where)
    /home/sylee/.conda/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /home/sylee/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:855 __array__
        " a NumPy call, which is not supported".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (SequenceToSequence/TransformerDecoder/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

```

and this is packages I have installed

```
# packages in environment at /home/sylee/.conda/envs/py37:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_tflow_select             2.1.0                       gpu  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py37h7f8727e_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
astor                     0.8.1            py37h06a4308_0  
astunparse                1.6.3                      py_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
asynctest                 0.13.0                     py_0  
attrs                     21.2.0             pyhd3eb1b0_0  
blas                      1.0                         mkl  
blinker                   1.4              py37h06a4308_0  
brotlipy                  0.7.0           py37h27cfd23_1003  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.10.26           h06a4308_2  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2021.10.8        py37h06a4308_0  
cffi                      1.14.6           py37h400218f_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.3              pyhd3eb1b0_0  
colorama                  0.4.4                    pypi_0    pypi
cryptography              3.4.8            py37hd23ed53_0  
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
dataclasses               0.8                pyh6d0b6a4_7  
frozenlist                1.2.0            py37h7f8727e_0  
gast                      0.3.3                    pypi_0    pypi
google-auth               1.33.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
grpcio                    1.42.0           py37hce63b2e_0  
h5py                      2.10.0           py37hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.8.2            py37h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
joblib                    1.1.0                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libprotobuf               3.17.2               h4ff587b_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
markdown                  3.3.4            py37h06a4308_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
multidict                 5.2.0            py37h7f8727e_2  
ncurses                   6.3                  h7f8727e_2  
neurst                    0.1.0                     dev_0    <develop>
numpy                     1.21.2           py37h20f2e39_0  
numpy-base                1.21.2           py37h79a1101_0  
oauthlib                  3.1.1              pyhd3eb1b0_0  
openssl                   1.1.1l               h7f8727e_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
pip                       21.2.2           py37h06a4308_0  
portalocker               2.3.2                    pypi_0    pypi
protobuf                  3.17.2           py37h295c915_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.1.0            py37h06a4308_0  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pysocks                   1.7.1                    py37_1  
python                    3.7.11               h12debd9_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h27cfd23_0  
regex                     2021.11.10               pypi_0    pypi
requests                  2.26.0             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
sacrebleu                 2.0.0                    pypi_0    pypi
sacremoses                0.0.46                   pypi_0    pypi
scipy                     1.7.1            py37h292c36d_2  
setuptools                58.0.4           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.37.0               hc218d9a_0  
tabulate                  0.8.9                    pypi_0    pypi
tensorboard               2.4.0              pyhc547734_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.4.1           gpu_py37ha2e99fa_0  
tensorflow-base           2.4.1           gpu_py37h29c2da4_0  
tensorflow-estimator      2.6.0              pyh7b7c402_0  
tensorflow-gpu            2.4.1                h30adc30_0  
termcolor                 1.1.0            py37h06a4308_1  
tk                        8.6.11               h1ccaba5_0  
tqdm                      4.62.3                   pypi_0    pypi
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
werkzeug                  2.0.2              pyhd3eb1b0_0  
wheel                     0.37.0             pyhd3eb1b0_1  
wrapt                     1.13.3           py37h7f8727e_2  
xz                        5.2.5                h7b6447c_0  
yarl                      1.6.3            py37h27cfd23_0  
zipp                      3.6.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7f8727e_4  
```

**Comment by zhaocq-nlp** [comment]
@ParkGiBum I inspected the installed packages of my environment and found maybe numpy<=1.19.5 should work.
